### ISSUE TITLE
Delete list item

### ISSUE THREAD

**Issue by rosik911** [Nothingface133/third_party#4]
С файла  Nothingface133/third_party/git/README.md удалить  3 пункт  с раздела How use autologin

**Comment by Nothingface133** [comment]
Не указал на ком баг, забыл добавить лейбл

**Comment by rosik911** [comment]
как ты лейбл добавил

**Comment by Nothingface133** [comment]
## В требованиях не правильный путь к файлу. Необходимо указывать локальный путь относительно директории third_party

**Comment by rosik911** [comment]
Исправил

**Comment by Nothingface133** [comment]
## Свяжи баг и коммит, что бы было понятно на основании чего ты заявил, что исправил

**Comment by Nothingface133** [comment]
### Вот таким образом
https://help.github.com/articles/closing-issues-via-commit-messages/
