### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by rosik911** [Nothingface133/third_party#5]
Test

**Comment by rosik911** [comment]
кАААк

**Comment by Nothingface133** [comment]
## Как я устанавливаю лейблы

1. Справа, если зайти в таск, есть 3 поля
2. Одно из них Labels
3. Так что, все просто уважаемый @rosik911

**Comment by rosik911** [comment]
Я не могу туда писать я их видел но они не активны

**Comment by Nothingface133** [comment]
## Туда нужно не писать, а выбирать из списка

**Comment by rosik911** [comment]
Test complite
